[package]
name = "piston"
version = "0.0.1"
authors = ["Mario Schroeder <spindizzy@outlook.com>"]

[dependencies]
find_folder = "0.3.0"
piston = "0.35.0"
piston2d-graphics = "0.23.0"
pistoncore-glutin_window = "0.42.0"
piston2d-opengl_graphics = "0.49.0"
piston2d-sprite = "0.40.0"