name: Rust

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: SDL2 install
      run: brew install sdl2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
